fixtures:
  forge_modules:
    apt: 'puppetlabs-apt'
    augeas: 'camptocamp-augeas'
    augeasproviders_core: 'herculesteam-augeasproviders_core'
    stdlib: 'puppetlabs-stdlib'
  symlinks:
    puppetserver: "#{source_dir}"
