fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    augeasproviders_core: https://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_shellvar: https://github.com/hercules-team/augeasproviders_shellvar.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    puppetserver: "#{source_dir}"
