---
language: ruby
sudo: false
cache: bundler
bundler_args: --without system_tests
script: ["bundle exec rake validate", "bundle exec rake lint", "bundle exec rake spec SPEC_OPTS='--format documentation'", "bundle exec rake metadata"]
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 1.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - env: BEAKER_set="debian-6-x86_64-openstack"
    bundler_args:
    script: '[ -z "${OS_AUTH_URL}" -o -z "${OS_USERNAME}" -o -z "${OS_PASSWORD}" -o -z "${OS_TENANT_NAME}" ] || bundle exec rspec spec/acceptance/*_spec.rb'
  - env: BEAKER_set="debian-7-x86_64-openstack"
    bundler_args:
    script: '[ -z "${OS_AUTH_URL}" -o -z "${OS_USERNAME}" -o -z "${OS_PASSWORD}" -o -z "${OS_TENANT_NAME}" ] || bundle exec rspec spec/acceptance/*_spec.rb'
  - env: BEAKER_set="centos-6-x86_64-openstack"
    bundler_args:
    script: '[ -z "${OS_AUTH_URL}" -o -z "${OS_USERNAME}" -o -z "${OS_PASSWORD}" -o -z "${OS_TENANT_NAME}" ] || bundle exec rspec spec/acceptance/*_spec.rb'
  - env: BEAKER_set="centos-7-x86_64-openstack"
    bundler_args:
    script: '[ -z "${OS_AUTH_URL}" -o -z "${OS_USERNAME}" -o -z "${OS_PASSWORD}" -o -z "${OS_TENANT_NAME}" ] || bundle exec rspec spec/acceptance/*_spec.rb'
notifications:
  email: false
deploy:
  provider: puppetforge
  user: camptocamp
  password:
    secure: "QcG6iRpDC8ojkaCsrO3HVyBCspKcc2lkxRlBLG5X61Gp8dytr36tzndldMsxGW4CgTnCWNuRlJhfKwvH8ObSR8hDZyQkNwzoOSRMIUM9SGvHKqCScSMW1gjdNvh/0oMt/WbZEcyN7/XIEmQqtMmXShBaQ0yWYdp3TvgfNSJ/NdM="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
env:
  global:
    - secure: MIw0kvfIT6Xk8eTmc45WknR5s8Z9CZAz2WqajHbPMAR/sh+rP+ZqcQccg8SbaXX7ophUmPTRJf7O+vP5OhHx72AVPP3xDcSpYfxk2ooNFkgnEJa5sOB4IjAypOl3V1lo2UbVx5C+PnEQA4lVyZESTwIz5nUgsLf27wfTECXFOHg=
    - secure: Vy2m2qv7xwLvxJRBzNdAzVycjPq8KcF8WX/+IaonDtBLdR5Jx1FkJrjk9TpgmC6htWm4mw/SYCGBmSpqG995SXzQpv7+QXlhK+JX/gId0r16rSyxwTfIXIttyJmwobzgxgXyaevkhpWUeX+/uL73Wqv54p7tLvQGR8ILhtlZfKQ=
    - secure: AFJtxKtspVlet0Zs6cqGKXD0f44PlPrdm4OGpol/CUqPbqPDGgwhLgiiCw4bxmifwAGYC/0Ss2cVfhDZub3wrL+C8I7gjo/0lQNlOwSlp9OkoBNNZHUzNmbf6hXgiIeBI7qx1xBzCN1No+TYerTUX0OheRU9c3yglCm9xIbsi7g=
    - secure: FWWJibHeniUwgTTcX27/nijGI9pH4Yx71yx1sUxB+Mb8u1yUhhKNlhe4G4UT84USKP1fMeko/PHgyBcgjLEsb5fj2MJi8Zj9hsM5ovHxZvUHFmEr2Auo7CiEB/K/gMbpSQbkxOdWAWzbGezNI/6NmWHl6DyBlGimyzUxtP9IJ80=
